%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\mario\Desktop\SCRD_SIM\Flight simulator\Rocket Parameters.xlsx
%    Worksheet: Aero Coeff
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/12/23 19:38:56

%% Import the data

%Read Aerodynamic Values
[~, ~, raw] = xlsread('Rocket Parameters.xlsx','Aero Coeff','A2:AF15');
[Reference, ~, ~] = xlsread('Rocket Parameters.xlsx','Aero Coeff','B18:B19');
[Xref,~,~]=xlsread('Rocket Parameters.xlsx','Aero Coeff','A20:B20');

%Read Mass Properties Values
[Initialmass,~,~]=xlsread('Rocket Parameters.xlsx','Mass Properties','A1:B1');
[Finalmass,~,~]=xlsread('Rocket Parameters.xlsx','Mass Properties','A2:B2');
[InitialInertia,~,~]=xlsread('Rocket Parameters.xlsx','Mass Properties','A5:C7');
[InertiaRate,~,~]=xlsread('Rocket Parameters.xlsx','Mass Properties','A10:C12');
[BurnoutInertia,~,~]=xlsread('Rocket Parameters.xlsx','Mass Properties','A15:C17');
[Initialcg,~,~]=xlsread('Rocket Parameters.xlsx','Mass Properties','A19:B19');
[Finalcg,~,~]=xlsread('Rocket Parameters.xlsx','Mass Properties','A20:B20');
[~,~,raw3]=xlsread('Rocket Parameters.xlsx','Mass Properties','A24:B32');    

%Read Thrust Values
[~, ~, raw2] = xlsread('Rocket Parameters.xlsx','Thrust Parameters','A3:B233');
[thrustvalues, ~, rawthrust]=xlsread('Rocket Parameters.xlsx','Thrust Parameters','F2:F6');

%Read Initial Conditions
[~, ~, raw4] = xlsread('Rocket Parameters.xlsx','Initial Conditions','B1:B20');

%Read Sloh Parameters
[~, ~, raw5] = xlsread('Rocket Parameters.xlsx','Slosh Parameters','F3:AB10');

%% Create output variable
data = reshape([raw{:}],size(raw));
data2 = reshape([raw2{:}],size(raw2));
data3 = reshape([raw3{:}],size(raw3));
data4 = reshape([raw4{:}],size(raw4));
data5 = reshape([raw5{:}],size(raw5));

%% Allocate imported array to column variable names
MACH = data(:,1);
CN = data(:,2);
CM = data(:,3);
CA = data(:,4);
CY = data(:,5);
CLN = data(:,6);
CLd = data(:,7);
CNa = data(:,8);
CMa = data(:,9);
CYb = data(:,10);
CLNb = data(:,11);
CLb = data(:,12);
CNq = data(:,13);
CMq = data(:,14);
CAq = data(:,15);
CYq = data(:,16);
CLNq = data(:,17);
CLLq = data(:,18);
CNr = data(:,19);
CMr = data(:,20);
CAr = data(:,21);
CYr = data(:,22);
CLNr = data(:,23);
CLLr = data(:,24);
CNp = data(:,25);
CMp = data(:,26);
CAp = data(:,27);
CYp = data(:,28);
CLNp = data(:,29);
CLLp = data(:,30);
CNadot = data(:,31);
CMadot = data(:,32);
Thrust_time = data2(1:8,1);
Thrust = data2(1:8,2);
Fuel_mass= thrustvalues(1);
Mass_flow=thrustvalues(2);
Ramup_time=thrustvalues(3);
BurnTime=thrustvalues(4);
Ae=thrustvalues(5);
Aref=Reference(1);
Lref=Reference(2);
Sample_time=0.1;
CG=data3(:,2);
Time_cg=data3(:,1);
Launch_site=data4(1);
Lat=data4(2);
Lon=data4(3);
Azimuth=deg2rad(data4(4));
Launch_angle=deg2rad(data4(5));
Time_slosh= data5(:,1);
omegajeta= data5(:,13);
omegalox= data5(:,23);
%% Clear temporary variables
clearvars data raw;
clearvars data2 data3 data4 data5 raw2 raw3 raw4 raw5;
clearvars rawthrust thrustvalues Reference;

load('Variantsconditions.mat')
% save('Parameters')
